[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT}"

[nixpacks]
enabled = true

[nixpacks.overrides]
php = """
pkgs.php82.withExtensions (exts: with exts; [
  gd
  mbstring
  xml
  zip
  pdo_mysql
])
"""
